### ISSUE TITLE
sth wrong happened in redblacktree.py

### ISSUE THREAD

**Issue by FlyingFatty** [dsysoev/fun-with-algorithms#1]
when I test your redblacktree.py code, I find sth wrong.
`    for i in range(1, 11):
        print('insert {} to tree'.format(i))
        tree.insert(i)
        print(tree)

    i = 5
    tree.delete(i)
    print(tree)`
And I do not know why. Thank you very much if you fix it up and give a reply. Best wishes.

**Comment by FlyingFatty** [comment]
main code

for i in range(1, 11):
    print('insert {} to tree'.format(i))
    tree.insert(i)
    print(tree)

    i = 5
    tree.delete(i)
    print(tree)

**Comment by FlyingFatty** [comment]
Traceback (most recent call last):
  File "redblacktree.py", line 388, in <module>
    tree.delete(i)
  File "redblacktree.py", line 257, in delete
    return self.__delete(node)
  File "redblacktree.py", line 285, in __delete
    self.__delete_fixup(x)
  File "redblacktree.py", line 289, in __delete_fixup
    while x != self.root and x.color == Node.BLACK:
AttributeError: 'NoneType' object has no attribute 'color'

**Comment by dsysoev** [comment]
Thank you for feedback. Please use last commit. Bug was fixed.

**Comment by FlyingFatty** [comment]
> Thank you for feedback. Please use last commit. Bug was fixed.

Thank you very much for your code and your reply. I learn a lot from your code. Thanks again.
